In [1]:
import numpy as np
arr=np.array([1,2,3,4])
np.arange(2,4,1)


array([2, 3])

In [19]:
import numpy as np
np.zeros((3,3),dtype=np.int32)

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [29]:
import numpy as np
np.ones((2,2),dtype=np.int32)

array([[1, 1],
       [1, 1]])

In [32]:
import numpy as np
np.array([1,2,3])

array([1, 2, 3])

In [36]:
import numpy as np
a=np.empty((3,3))
a

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [39]:
import numpy as np
np.eye((2))

array([[1., 0.],
       [0., 1.]])

In [16]:
import numpy as np
a=np.array([(1,3,4),(2,1,4),(2,45,56)])
a

array([[ 1,  3,  4],
       [ 2,  1,  4],
       [ 2, 45, 56]])

In [49]:
import numpy as np
a=np.array([1,2,3,4,5,6,7,8]).reshape(2,4)
a

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [51]:
import numpy as np
array=np.arange(8).reshape(2,4)
array

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [1]:
a=np.arange(3)
a

NameError: name 'np' is not defined

In [21]:
import numpy as np
y=np.array([(2,2,3,4),(1,2,3,4)])
a=np.ones_like(y)
a


array([[1, 1, 1, 1],
       [1, 1, 1, 1]])

In [63]:
import numpy as np
y=np.ones((30,30))
x=np.ones_like(y)
k=x[9:-1,2:6]
j=k.flatten()
j
#for d in k.flatten(order='K'):
 #   print (d)


array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [73]:
a=np.arange(8).reshape(2,4)
for i in np.nditer(a,flags=['external_loop']):
    print(i)


[0 1 2 3 4 5 6 7]


In [75]:
a=np.arange(16).reshape(4,4)
for x in np.nditer(a,order='F',flags=['external_loop']):
    print(x)

[ 0  4  8 12]
[ 1  5  9 13]
[ 2  6 10 14]
[ 3  7 11 15]


In [81]:
c=np.arange(4).reshape(2,2)
for k in np.nditer(c,op_flags=['readwrite']):
    k[...]=k*k
    


In [83]:
c

array([[0, 1],
       [4, 9]])

In [93]:
array=np.array([[1,2,3,4,'dded'],[2,3,4,5,'gduwgdu']])
np.shape(array)
k=array.T
k.ravel()
np.shape(k)


(5, 2)

In [97]:
kr=np.arange(12)
np.split(kr,(4,10))


[array([0, 1, 2, 3]), array([4, 5, 6, 7, 8, 9]), array([10, 11])]

In [113]:
j=np.array([(1,2,3,4),(5,6,7,8)])
np.hsplit(j,4)

[array([[1],
        [5]]), array([[2],
        [6]]), array([[3],
        [7]]), array([[4],
        [8]])]

In [8]:
import numpy as np
h=np.arange(4).reshape(2,2)
np.vsplit(h,2)

[array([[0, 1]]), array([[2, 3]])]

In [12]:
import numpy as np
from scipy import ndimage
arra=ndimage.imread('datasets/koala.jpg')

AttributeError: module 'scipy.ndimage' has no attribute 'imread'

In [14]:
!pip install scipy

In [16]:
def computeHCF(num1, num2):
    
    return max([i+1 for i in range(min([num1, num2])) if (num1 % (i+1) == 0) and (num2 % (i+1) == 0) ])

In [19]:
computeHCF(12,14)

2

In [28]:
list=[12,14]
for i in range(min[12,14]):
    if((12%(i+1)==0) and (14%(i+1)==0)):  
    print(i+1)      

IndentationError: expected an indented block (<ipython-input-28-116c74afba1a>, line 4)

In [47]:
num1=100
num2=200
a=min(num1,num2)
for i in range(a):
    if(num1%(i+1)==0) and (num2%(i+1)==0):
        
        print(i+1)


1
2
4
5
10
20
25
50
100


In [3]:
def print_one(name):
    print("hello {}".format(name))
    
print_one(1)

hello 1


In [2]:
print_one('bdud')

NameError: name 'print_one' is not defined

In [6]:
l=range(18)
%timeit [i**2 for i in  l]

18.9 µs ± 2.19 µs per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [11]:
import numpy as np
a=np.arange(18)
%timeit a**2

1.85 µs ± 186 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [18]:
import numpy as np
b = np.array([1,2,3,4,5])
b.ndim
b.shape

(5,)

In [25]:
import numpy as np
c=np.array([[[1,2,3], [2,3,4]],[[1,2,3],[1,2,3]]])
c.ndim
c.shape
len(c)


2

In [28]:
import numpy as np
a=np.arange(1,10,2)
a

array([1, 3, 5, 7, 9])

In [31]:
import numpy as np
a=np.linspace(1,2,6)
a

array([1. , 1.2, 1.4, 1.6, 1.8, 2. ])

In [33]:
import numpy as np
a=np.ones([2,2])
a

array([[1., 1.],
       [1., 1.]])

In [38]:
import numpy as np
a=np.zeros[[2,2]]
a


TypeError: 'builtin_function_or_method' object is not subscriptable

In [41]:
import numpy as np
a=np.diag([1,2,3,4,5])
a
np.diag(a)

array([1, 2, 3, 4, 5])

In [45]:
a=np.random.rand(4)
a

array([0.77992316, 0.25362346, 0.66467982, 0.82783592])

In [48]:
import numpy as np
a=np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [63]:
import numpy as np
a=np.arange(10)
a[1:8:2]
a[5:]=10
a
b=np.arange(10)
a[::]=b[::-1]
a[::-1]


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [59]:
import numpy as np
a=np.arange(10)
b=a[::2]
b
#np.shares_memory(b,a)

array([0, 2, 4, 6, 8])

In [71]:
import numpy as np
c=np.arange(12)
d=c[::2].copy()
d
np.shares_memory(c,d)

False

In [83]:
import numpy as np
k=np.random.randint(0,10,15)
k
mask=(k%2==0)
a=k[mask]
a
np.shares_memory(k,a)

False

In [89]:
import numpy as np
j=np.arange(10)
mask=(j%2==0)
j[mask]=0
j


array([0, 1, 0, 3, 0, 5, 0, 7, 0, 9])

In [98]:
import numpy as np
n=np.arange(0,100,10)
n[[2,3,4,4,5]]
n[[4,5]]=-100
n


array([   0,   10,   20,   30, -100, -100,   60,   70,   80,   90])

In [69]:
import numpy as np
i=np.array([[[1,2],[2,3]],[[1,2],[2,3]]])
k=np.array([[[3,4],[6,4]],[[1,2],[2,3]]])
j=i+k
j

array([[[4, 6],
        [8, 7]],

       [[2, 4],
        [4, 6]]])

In [4]:
import numpy as np
a=np.array([1,2,3])
a+1

array([2, 3, 4])

In [10]:
import numpy as np
a=np.arange(10)
a
np.sin(a)
np.cos(a)
np.exp(a)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03])

In [19]:
import numpy as np
a=np.array([[1,2],[2,3]])
a.sum(axis=0)
a.min()
a.max()
a.argmin()
a.argmax()

3

In [2]:
import numpy as np
a=np.array([1,2,3])
b=np.array([4,5,6])
c=np.array([0,0,0])
((a<=b)&(b>=c)).all()

True

In [23]:
import numpy as np
k=np.array([[5,6,1],[1,2,3]])
k.mean()
np.median(k,axis=1)
np.median(k,axis=0)
np.median(k)

2.5

In [25]:
import numpy as np
j=np.zeros(4)
j

array([0., 0., 0., 0.])

In [121]:
import numpy as np
data=np.loadtxt('dob.txt')
#np.tile(np.arange(data),(3,1))
year,vinod,dob=data.T
print(year)
print(vinod)
print(dob)

[1996. 1997. 1994. 1995.]
[23. 24. 34. 35.]
[1997. 1998. 1234. 1887.]


In [60]:
pop=data.T[1:,1:]
pop.std(axis=1)
np.argmax(pop,axis=1)
np.median(pop,axis=1)

array([  34., 1887.])

In [70]:
import numpy as np
a=np.tile(np.arange(0,40,10),(3,2))
print(a)


[[ 0 10 20 30  0 10 20 30]
 [ 0 10 20 30  0 10 20 30]
 [ 0 10 20 30  0 10 20 30]]


In [82]:
import numpy as np
b= np.tile(np.arange(0,10,2),(1,2))
a=np.array([1,2,3,4,5,6,7,8,9,0])
b+a

array([[ 1,  4,  7, 10, 13,  6,  9, 12, 15,  8]])

In [1]:
import numpy as np
b=np.array([1,2,3,4])
b=b[:,np.newaxis]
b
a=np.array([1,2])
a+b

array([[2, 3],
       [3, 4],
       [4, 5],
       [5, 6]])

In [22]:
import  numpy as np
a=np.arange(0,8,3)
a
a=a[:,np.newaxis]
a
b=np.tile(np.array([[1,2,3]]),(3,1))
c=np.array([1,2,3])
c=c[:,np.newaxis]
a+b


array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [29]:
import numpy as np
#a=np.arange([0,10,2])
a=np.tile(np.arange(0,10,2),(3,2))
b=np.array([1,2,3,4,5,6,7,8,9,10])
a+b

array([[ 1,  4,  7, 10, 13,  6,  9, 12, 15, 18],
       [ 1,  4,  7, 10, 13,  6,  9, 12, 15, 18],
       [ 1,  4,  7, 10, 13,  6,  9, 12, 15, 18]])

In [34]:
import numpy as np
a=np.arange((0,10,2),(0,6,2))
a

TypeError: arange: scalar arguments expected instead of a tuple.

In [62]:
import numpy as np
a=np.array([[1,2,3],[3,2,1]])
a.ravel()
b=a.ravel()
b.reshape(3,2)



array([[1, 2],
       [3, 3],
       [2, 1]])

In [68]:
a[0,0] = 100
b[1]=101
a

array([[100, 101,   3],
       [  3,   2,   1]])

In [75]:
import numpy as np
a=np.arange(24).reshape(4,3,2)
np.shape(a)
a
a[1,1,1]

9

In [81]:
import numpy as np
a=np.arange(4)
a.resize((8))
a
b=a
a.resize(4)
a

ValueError: cannot resize an array that references or is referenced
by another array in this way.
Use the np.resize function or refcheck=False

In [105]:
import numpy as np
v=np.array([[1,2,3],[3,2,2]])
u=np.sort(v,axis=1)
u[:,1:]=12
u

array([[ 1, 12, 12],
       [ 2, 12, 12]])

In [1]:
import numpy as np
a=np.array([[1,2,3],[8,4,5],[12]])
j,i=np.argsort(a)
j






ValueError: too many values to unpack (expected 2)

In [14]:
import numpy as np
a=np.zeros_like((3,3))
a

array([0, 0])